/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../driver/inc/stm32f407xx_gpio_drivers.h"

void delay(){
	for(uint32_t i =0; i<=300000; i++){

	}
}

/**
 * @brief this is main function
 * @return this function returns zero
 */
int main(void) {
	GPIO_Handle_t GPIOHandle;
	GPIOHandle.pGPIOx = GPIOD;
	GPIOHandle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIOHandle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT;
	GPIOHandle.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIOHandle.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIOHandle.GPIO_PinConfig.GPIO_PuPdControl = GPIO_NO_PUPD;
	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GPIOHandle);

	while(1){
		GPIO_ToggleOutPutPin(GPIOD, GPIO_PIN_NO_12);
		delay();
	}
	return 0;
}
